### ISSUE TITLE
Toolbar disappears forever after first scroll event

### ISSUE THREAD

**Issue by SWalls** [JohannBlake/JBHeaderScroll#1]
Thanks for making this library!

Upon opening my app, the toolbar is visible as usual, but as soon as I scroll a tiny little bit (not enough to cause the hide animation), the toolbar becomes invisible and is replaced by just a blank white box. I think this might be a problem with `bringToFront()` but I'm not sure. Other than it turning into a white box, everything else seems to be working absolutely fine. The view's top margin changes appropriately while scrolling as expected.

Here's the code for the function that is called in my `onCreate()` method. It's copy-pasted directly from your README file, with a few slight changes. Just so you know, I'm using a `RecyclerView` instead of a `ListView`, but these are essentially the same thing, so it's easily supported by your library.

```java
private void setupJBHeaderScroll() {
    toolbar.getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener()
    {
        @Override
        public void onGlobalLayout()
        {
            try
            {
                scroller.setY(toolbar.getHeight());
                jbHeaderScroll = new JBHeaderScroll(toolbar, 0);
                jbHeaderScroll.registerScroller(scroller, new JBHeaderScroll.IJBHeaderScroll()
                {
                    @Override
                    public void onReposition(float top, boolean scrollingUp, float scrollDelta)
                    {
                        try
                        {
                            LibraryFragment currentPageFragment = pagerAdapter.getCurrentFragment();
                            RecyclerView playList = currentPageFragment.getRecyclerView();
                            LinearLayoutManager listLayoutManager = currentPageFragment.getRecyclerViewLayoutManager();

                            int pos = listLayoutManager.findFirstVisibleItemPosition();
                            float y = playList.getChildAt(pos).getY();

                            // The list's view top edge must be adjusted during scrolling.
                            // IMPORTANT: Make sure you use the correct type of LayoutParams which is the type that applies to the parent
                            // container of the listview.

                            // When the user releases their finger while scrolling very slowly, the jitter from their finger
                            // may result in a slight amount of scrolling downward. This can result in a side effect of the
                            // header animating down when it might have animated up depending on its current position. To
                            // avoid this, avoid repositioning the scroller for small amounts of scrolling. You may need to
                            // play with this value.

                            if (scrollingUp || (!scrollingUp && (scrollDelta > 5)))
                            {
                                LinearLayout.LayoutParams layoutParams = new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, LinearLayout.LayoutParams.MATCH_PARENT);
                                layoutParams.setMargins(0, (int) top, 0, 0);
                                scroller.setLayoutParams(layoutParams);
                                toolbar.bringToFront(); // Necessary if your scroller is rendered last.
                            }
                        }
                        catch (Exception e)
                        {
                            LogP.e(LogP.TAG_SCRIPTREADER, "onReposition: " + e.toString());
                        }
                    }

                    @Override
                    public int onHeaderBeforeAnimation(boolean scrollingUp, float scrollDelta)
                    {
                        return JBHeaderScroll.ANIMATE_HEADER_USE_DEFAULT;
                    }

                    @Override
                    public void onHeaderAfterAnimation(boolean animatedUp, float scrollDelta)
                    {
                    }
                });

                scroller.setJBHeaderRef(jbHeaderScroll);
                toolbar.getViewTreeObserver().removeOnGlobalLayoutListener(this);
            }
            catch (Exception e)
            {
                LogP.e(LogP.TAG_SCRIPTREADER, "onGlobalLayout: " + e.toString());
            }
        }
    });
}
```

Does this look right to you, or am I doing something wrong?

**Comment by JohannBlake** [comment]
How does the demo app I wrote work? Do all the demos work? What version of Android are you using? Can you post your code to Github with everything stripped out except the stuff related to scrolling the recyclerview? If you can, I can download it and try it out locally to see where the problem is.

**Comment by SWalls** [comment]
Ah, the solution was simple. I had to change two things. The parent view containing both the toolbar and the scroller was a `LinearLayout`, not a `RelativeLayout` as in your demos. Also, I did not include the `android:layout_below="@id/toolbar"` attribute of my scroller as in your demos. It was not apparent from your README that both of these are **required** for this to function properly. Perhaps consider adding something about this? Thanks again!

**Comment by JohannBlake** [comment]
I updated the README.md file. Actually, your code would have generated an exception when using the wrong LayoutParams. You would have caught that if you had enabled breaking on ALL Exceptions in Android Studio.

**Comment by SWalls** [comment]
Sorry, you misunderstood. I was using both

**Comment by SWalls** [comment]
Sorry, you misunderstood. I was using both a `LinearLayout` as the parent view, AND using `LinearLayout.LayoutParams`. No exception was being generated, but the Toolbar was still invisible. Changing both the parent view and the LayoutParams to `RelativeLayout` was what fixed the issue; it seems using LinearLayout for a parent does not work as expected.
